// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzcfdafdipmkgbolpytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6Y2ZkYWZkaXBta2dib2xweXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NzIwMDEsImV4cCI6MjA3NDQ0ODAwMX0.ztqeBhYrt9MmLGnGB9cl8r1BwFqv4AdLgHFlLdWxBTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});